### ISSUE TITLE
Insert into hive table from ES fails 

### ISSUE THREAD

**Issue by xolantumy** [elasticsearch/elasticsearch-hadoop#354]
I'm following the tutorial here: https://github.com/hortonworks/hadoop-tutorials/blob/master/Community/T07_Elasticsearch_Hadoop_Integration.md

I downloaded Sandbox with HDP 2.2 and I am running it on Mac OS X Yosemite from VirtualBox. It runs fine. I installed elasticsearch 1.4.2 on the Sandbox VM. I setup one index on ES called demo. I am using the elasticsearch-hadoop jars. Sandbox is running Hive 0.14.0
I then tried to run the queries separately. I created the table logs. I also managed to create the external table eslogs. 

Now I am trying insert the data from logs into eslogs. 

INSERT OVERWRITE TABLE eslogs SELECT s.time, s.ext, s.ip, s.req, s.res, s.agent FROM logs s;

Each time I try, the result of the query is empty. The results show me that the query has failed. There is no message explaining why it has failed. I would guess that Hive and ES are not talking to each other? I have tried elasticsearch-hadoop-1.3.0.M1.jar, elasticsearch-hadoop-2.0.2.jar and elasticsearch-hadoop-2.1.0.Beta3.jar. I have also tried insert data values of my own into eslogs. 

INSERT INTO TABLE eslogs VALUES ( "12", "NEW", "US", "FREE", "LOT", "PEP" )

This also fails. I'm not sure how to proceed.

**Comment by costin** [comment]
@xolantumy we don't provide support for documentation/projects outside es-hadoop proper - it's best to direct your questions to the repo owners. In case there is a problem, you should get an exception - the fact that you get back `NULL` typically indicates a mapping problem - in other words you are inserting the data in ES but when you select it, because there isn't any found, null is returned (note this behaviour can be changed).

I recommend reading the Hive chapter in the es-hadoop [docs](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/current/hive.html) and start with a basic example that just inserts some data in and gets it out. Between the docs and the tutorial you are looking at, hopefully you'll be able to find the error.
Note that the docs also mention how to troubleshoot potential es-hadoop issues.

If you have more questions, please reach out on the mailing list and/or IRC - the issue tracker is focused on development mainly.

Thanks!
