### ISSUE TITLE
Indexing ES using rdd over https connection

### ISSUE THREAD

**Issue by geetanjaligg** [elasticsearch/elasticsearch-hadoop#371]
I have secured ES + Kibana with nginx, so it's password protected and served over SSL. 
```
sparkconf.set("es.index.auto.create", "true")
sparkconf.set("es.nodes","xx.xxx.xxx.xxx")
sparkconf.set("es.port","9200")

log_map.filter(_!=None).saveToEs("dataset/logs")
```
doesn't seem to work. 

Any suggestions?

**Comment by costin** [comment]
@geetanjaligg Es-hadoop needs to be configured to use SSL since otherwise it relies on HTTP not HTTPS. It also can be configured to support proxies or basic authentication.
See the reference documentation for more information [here](http://www.elasticsearch.org/guide/en/elasticsearch/hadoop/2.1.Beta/configuration.html#_ssl).
In the future, for questions please use the mailing list or the IRC not the issue tracker. Thank you.
